group: travis_latest
branches:
  only:
    - master
    - feat/offline-only-index
    - travis_stages
osx_image: xcode9
language: objective-c
env:
  matrix:
    - FASTLANE_TARGET="mac"
    - FASTLANE_TARGET="ios"
    - FASTLANE_TARGET="tv"
install: true
before_script:
  - gem install xcpretty -N
  - gem update fastlane

jobs:
  include:
    - stage: test
      script:
        - set -o pipefail
        - fastlane ${FASTLANE_TARGET} test
    - stage: dummy
      script: echo "hello"

