# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "9.2.0"
    
    working_directory: /Users/algolia/output
    
    steps:
      - checkout
      # Install Pods
      # - run:
      #     name: Install Pods
      #     command: pod install
      # - run: bundle install

  test_ios:
    macos:
      xcode: "9.2.0"
    
    working_directory: /Users/algolia/output

    steps:
      - run:
          name: Build and run iOS tests
          command: bundle exec fastlane ios test

  test_mac:
    macos:
      xcode: "9.2.0"

    working_directory: /Users/algolia/output

    steps:
      - run:
          name: Build and run MacOS tests
          command: bundle exec fastlane mac test

  test_tv:
    macos:
      xcode: "9.2.0"

    working_directory: /Users/algolia/output

    steps:
      - run:
          name: Build and run tvOS tests
          command: bundle exec fastlane tv test

  test_watch:
    macos:
      xcode: "9.2.0"

    working_directory: /Users/algolia/output
    
    steps:
      - run:
          name: Build and run watchOS tests
          command: bundle exec fastlane watch test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_ios:
          requires:
            - build
      - test_mac:
          requires:
            - build
      - test_watch:
          requires:
            - build
      - test_tv:
          requires:
            - build
